import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';
import { AsyncLocalStorage } from 'async_hooks';
import { v4 as uuidv4 } from 'uuid';

/**
 * Request context stored in AsyncLocalStorage for the current request
 * Accessible throughout the entire request lifecycle
 */
export interface RequestContext {
  requestId: string;
  correlationId: string;
  sessionId?: string;
  userId?: string;
  traceId?: string;
  spanId?: string;
  feature?: string;
  startTime: number;
}

/**
 * AsyncLocalStorage instance for request context
 * Provides isolated context for each request across async operations
 */
export const requestContextStorage = new AsyncLocalStorage<RequestContext>();

/**
 * Middleware to initialize request context using AsyncLocalStorage
 * Captures correlation IDs, session IDs, and OpenTelemetry trace context
 */
@Injectable()
export class RequestContextMiddleware implements NestMiddleware {
  use(req: Request, res: Response, next: NextFunction) {
    // Generate unique request ID for this specific request
    const requestId = uuidv4();

    // Extract or generate correlation ID (persists across multiple requests from same client session)
    const correlationId = (req.headers['x-correlation-id'] as string) || requestId;

    // Extract session ID (generated by frontend, persists across browser session)
    const sessionId = req.headers['x-session-id'] as string;

    // Extract OpenTelemetry trace context from W3C Trace Context format
    // Format: traceparent: 00-<trace-id>-<span-id>-<trace-flags>
    const traceParent = req.headers['traceparent'] as string;
    let traceId: string | undefined;
    let spanId: string | undefined;

    if (traceParent) {
      const parts = traceParent.split('-');
      if (parts.length === 4) {
        traceId = parts[1]; // 32-character trace ID
        spanId = parts[2]; // 16-character span ID
      }
    }

    // Initialize request context
    const context: RequestContext = {
      requestId,
      correlationId,
      sessionId,
      traceId,
      spanId,
      startTime: Date.now(),
    };

    // Set response headers for client-side correlation
    res.setHeader('X-Request-ID', requestId);
    res.setHeader('X-Correlation-ID', correlationId);

    // Run the rest of the request handling within this context
    requestContextStorage.run(context, () => {
      next();
    });
  }
}

/**
 * Get the current request context from AsyncLocalStorage
 * Returns undefined if called outside of a request context
 */
export function getRequestContext(): RequestContext | undefined {
  return requestContextStorage.getStore();
}

/**
 * Set user information in the current request context
 * Called by authentication guards after user is validated
 */
export function setRequestContextUser(userId: string): void {
  const context = getRequestContext();
  if (context) {
    context.userId = userId;
  }
}

/**
 * Set feature area in the current request context
 * Used for categorizing requests (auth, analysis, mapping, etc.)
 */
export function setRequestContextFeature(feature: string): void {
  const context = getRequestContext();
  if (context) {
    context.feature = feature;
  }
}
