
import React from 'react';
import { ClusterRecommendation, SparkConfigRecommendation, QueryRewrite } from '../../shared/types';
import { Server, Settings, Code, ArrowRight, Copy, Check } from 'lucide-react';

interface Props {
  clusterRec?: ClusterRecommendation;
  configRec?: SparkConfigRecommendation;
  rewrites?: QueryRewrite[];
}

export const AdvancedInsights: React.FC<Props> = ({ clusterRec, configRec, rewrites }) => {
  const [copied, setCopied] = React.useState<string | null>(null);
  const copyToClipboard = (text: string, id: string) => { navigator.clipboard.writeText(text); setCopied(id); setTimeout(() => setCopied(null), 2000); };

  return (
    <div className="space-y-8 animate-fade-in">
      {clusterRec && (<section className="bg-white rounded-3xl border border-slate-200 p-8 shadow-sm"><div className="flex items-center gap-3 mb-6"><div className="p-2 bg-blue-100 text-blue-700 rounded-lg"><Server className="w-6 h-6" /></div><h3 className="text-xl font-bold text-slate-900">Cluster Right-Sizing Advisor</h3></div><div className="flex flex-col md:flex-row gap-8 items-center"><div className="flex-1 w-full bg-slate-50 rounded-2xl p-6 border border-slate-200"><div className="text-xs font-bold text-slate-500 uppercase mb-2">Current Config</div><div className="text-2xl font-bold text-slate-900">{clusterRec.current.nodes}x {clusterRec.current.type}</div><div className="text-slate-500 text-sm mt-1">${clusterRec.current.costPerHour.toFixed(2)}/hr</div></div><ArrowRight className="w-8 h-8 text-slate-300 hidden md:block" /><div className="flex-1 w-full bg-emerald-50 rounded-2xl p-6 border border-emerald-100 relative overflow-hidden"><div className="absolute top-0 right-0 bg-emerald-500 text-white text-xs font-bold px-3 py-1 rounded-bl-xl">Recommended</div><div className="text-xs font-bold text-emerald-700 uppercase mb-2">Optimized Config</div><div className="text-2xl font-bold text-emerald-900">{clusterRec.recommended.nodes}x {clusterRec.recommended.type}</div><div className="text-emerald-700 text-sm mt-1">${clusterRec.recommended.costPerHour.toFixed(2)}/hr</div></div></div><div className="mt-6 p-4 bg-blue-50 rounded-xl border border-blue-100 text-sm text-blue-900"><strong>Reasoning:</strong> {clusterRec.reasoning} <br/><span className="text-blue-700 mt-1 block">Expected Impact: {clusterRec.expectedImprovement}</span></div></section>)}
      {configRec && (<section className="bg-white rounded-3xl border border-slate-200 p-8 shadow-sm"><div className="flex items-center gap-3 mb-6"><div className="p-2 bg-orange-100 text-orange-700 rounded-lg"><Settings className="w-6 h-6" /></div><h3 className="text-xl font-bold text-slate-900">Auto-Generated Spark Configs</h3></div><div className="bg-slate-900 rounded-2xl p-6 relative overflow-hidden group"><div className="absolute top-4 right-4"><button onClick={() => copyToClipboard(Object.entries(configRec.configs).map(([k,v]) => `${k} = ${v}`).join('\n'), 'config')} className="p-2 bg-white/10 hover:bg-white/20 text-white rounded-lg transition-colors">{copied === 'config' ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}</button></div><pre className="font-mono text-sm text-blue-300">{Object.entries(configRec.configs).map(([key, value]) => (<div key={key} className="mb-1"><span className="text-purple-400">spark.conf.set</span>(<span className="text-emerald-300">"{key}"</span>, <span className="text-orange-300">"{value}"</span>)</div>))}</pre></div><div className="mt-4 text-sm text-slate-600 font-medium italic">Impact: {configRec.estimatedImpact}</div></section>)}
      {rewrites && rewrites.length > 0 && (<section className="bg-white rounded-3xl border border-slate-200 p-8 shadow-sm"><div className="flex items-center gap-3 mb-6"><div className="p-2 bg-fuchsia-100 text-fuchsia-700 rounded-lg"><Code className="w-6 h-6" /></div><h3 className="text-xl font-bold text-slate-900">Smart Query Rewrites</h3></div><div className="space-y-6">{rewrites.map((rw, i) => (<div key={i} className="border border-slate-200 rounded-2xl overflow-hidden"><div className="bg-slate-50 px-6 py-3 border-b border-slate-200 flex justify-between items-center"><div className="text-xs font-bold text-slate-500 uppercase tracking-wide">Strategy: {rw.strategy}</div><div className="text-xs font-bold text-emerald-600 bg-emerald-50 px-2 py-1 rounded border border-emerald-100">Speedup: {rw.expectedSpeedup}</div></div><div className="grid grid-cols-1 md:grid-cols-2 divide-y md:divide-y-0 md:divide-x divide-slate-200"><div className="p-4 bg-red-50/30"><div className="text-xs font-bold text-red-700 mb-2">ORIGINAL</div><pre className="text-xs font-mono text-slate-800 whitespace-pre-wrap">{rw.original}</pre></div><div className="p-4 bg-emerald-50/30"><div className="text-xs font-bold text-emerald-700 mb-2">REWRITTEN</div><pre className="text-xs font-mono text-slate-800 whitespace-pre-wrap">{rw.rewritten}</pre></div></div><div className="px-6 py-3 bg-slate-50 border-t border-slate-200 text-xs text-slate-600"><strong>Tradeoffs:</strong> {rw.tradeoffs}</div></div>))}</div></section>)}
    </div>
  );
};
