import React, { useState } from 'react';
import { OptimizationTip, Severity } from '../../shared/types';
import { AlertTriangle, CheckCircle, Zap, Copy, Code } from 'lucide-react';

interface Props {
  optimizations: OptimizationTip[];
}

export const OptimizationList: React.FC<Props> = ({ optimizations }) => {
  const [copiedIdx, setCopiedIdx] = useState<number | null>(null);
  const totalTimeSaved = optimizations.reduce((sum, opt) => sum + (opt.estimated_time_saved_seconds || 0), 0);
  const totalCostSaved = optimizations.reduce((sum, opt) => sum + (opt.estimated_cost_saved_usd || 0), 0);
  const avgConfidence = optimizations.reduce((sum, opt) => sum + (opt.confidence_score || 0), 0) / optimizations.length;
  const copyToClipboard = (text: string, idx: number) => { navigator.clipboard.writeText(text); setCopiedIdx(idx); setTimeout(() => setCopiedIdx(null), 2000); };

  return (
    <div className="space-y-6 animate-fade-in">
      <h3 className="text-2xl font-bold text-slate-900 dark:text-white flex items-center gap-3 mb-8"><div className="p-2 bg-orange-100 dark:bg-orange-900/30 rounded-xl border border-orange-200 dark:border-orange-800 shadow-sm"><Zap className="w-6 h-6 text-orange-600 dark:text-orange-400" /></div>Performance Recommendations</h3>
      {(totalTimeSaved > 0 || totalCostSaved > 0) && (
        <div className="bg-gradient-to-br from-orange-50 to-amber-50 dark:from-orange-950/30 dark:to-amber-950/30 rounded-3xl shadow-sm border border-orange-200 dark:border-orange-800 p-6 mb-8">
          <div className="flex items-center gap-3 mb-4"><div className="p-2 bg-white dark:bg-slate-800 rounded-xl shadow-sm"><Zap className="w-5 h-5 text-orange-600 dark:text-orange-400" /></div><h4 className="font-bold text-slate-900 dark:text-white text-lg">Total Optimization Potential</h4></div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="bg-white dark:bg-slate-800 p-4 rounded-2xl border border-orange-100 dark:border-slate-700 shadow-sm"><div className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wide mb-1">Time Reduction</div><div className="text-2xl font-bold text-blue-700 dark:text-blue-400">{totalTimeSaved < 60 ? `${totalTimeSaved.toFixed(0)}s` : totalTimeSaved < 3600 ? `${(totalTimeSaved / 60).toFixed(1)}m` : `${(totalTimeSaved / 3600).toFixed(1)}h`}</div><div className="text-xs text-slate-600 dark:text-slate-400 mt-1">per execution</div></div>
            <div className="bg-white dark:bg-slate-800 p-4 rounded-2xl border border-orange-100 dark:border-slate-700 shadow-sm"><div className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wide mb-1">Cost Savings</div><div className="text-2xl font-bold text-emerald-700 dark:text-emerald-400">${totalCostSaved.toFixed(2)}</div><div className="text-xs text-slate-600 dark:text-slate-400 mt-1">per run · ${(totalCostSaved * 365).toFixed(0)}/year if daily</div></div>
            <div className="bg-white dark:bg-slate-800 p-4 rounded-2xl border border-orange-100 dark:border-slate-700 shadow-sm"><div className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wide mb-1">Avg Confidence</div><div className="flex items-baseline gap-2"><div className={`text-2xl font-bold ${avgConfidence >= 80 ? 'text-emerald-700 dark:text-emerald-400' : avgConfidence >= 60 ? 'text-amber-700 dark:text-amber-400' : 'text-slate-700 dark:text-slate-300'}`}>{avgConfidence.toFixed(0)}%</div><div className="text-xs text-slate-600 dark:text-slate-400">across {optimizations.length} issues</div></div></div>
          </div>
        </div>
      )}
      {optimizations.map((opt, idx) => (
        <div key={idx} className={`bg-white dark:bg-slate-900 rounded-3xl shadow-sm border overflow-hidden group transition-all hover:shadow-md ${opt.severity === Severity.HIGH ? 'border-red-200 dark:border-red-900' : 'border-slate-200 dark:border-slate-800 hover:border-orange-200 dark:hover:border-orange-800'}`}>
          <div className={`p-6 flex flex-col md:flex-row gap-5 justify-between items-start border-l-4 ${opt.severity === Severity.HIGH ? 'border-red-500 bg-red-50 dark:bg-red-950/20' : opt.severity === Severity.MEDIUM ? 'border-amber-500 bg-amber-50 dark:bg-amber-950/20' : 'border-emerald-500 bg-emerald-50 dark:bg-emerald-950/20'}`}>
            <div className="flex gap-5 flex-1">
              <div className="mt-1 flex-shrink-0">{opt.severity === Severity.HIGH && <div className="p-2 bg-white dark:bg-slate-800 text-red-600 dark:text-red-400 rounded-xl border border-red-200 dark:border-red-900 shadow-sm"><AlertTriangle className="w-6 h-6" /></div>}{opt.severity === Severity.MEDIUM && <div className="p-2 bg-white dark:bg-slate-800 text-amber-600 dark:text-amber-400 rounded-xl border border-amber-200 dark:border-amber-900 shadow-sm"><AlertTriangle className="w-6 h-6" /></div>}{opt.severity === Severity.LOW && <div className="p-2 bg-white dark:bg-slate-800 text-emerald-600 dark:text-emerald-400 rounded-xl border border-emerald-200 dark:border-emerald-900 shadow-sm"><CheckCircle className="w-6 h-6" /></div>}</div>
              <div className="flex-1">
                <div className="flex items-start justify-between gap-4 mb-2"><h4 className="text-xl font-bold text-slate-900 dark:text-white tracking-tight">{opt.title}</h4>{opt.confidence_score && (<div className="flex items-center gap-1 px-2 py-1 bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 text-xs"><span className="text-slate-500 dark:text-slate-400 font-semibold">Confidence:</span><span className={`font-bold ${opt.confidence_score >= 80 ? 'text-emerald-600 dark:text-emerald-400' : opt.confidence_score >= 60 ? 'text-amber-600 dark:text-amber-400' : 'text-slate-600 dark:text-slate-400'}`}>{opt.confidence_score}%</span></div>)}</div>
                <p className="text-slate-800 dark:text-slate-300 mt-2 leading-relaxed text-base font-medium">{opt.description}</p>
                {(opt.estimated_time_saved_seconds || opt.estimated_cost_saved_usd || opt.implementation_complexity) && (<div className="mt-4 flex flex-wrap gap-3">{opt.estimated_time_saved_seconds && (<div className="flex items-center gap-2 px-3 py-1.5 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg"><span className="text-xs text-blue-600 dark:text-blue-400 font-bold">⏱️ Time Saved:</span><span className="text-sm font-bold text-blue-800 dark:text-blue-300">{opt.estimated_time_saved_seconds < 60 ? `${opt.estimated_time_saved_seconds.toFixed(0)}s` : `${(opt.estimated_time_saved_seconds / 60).toFixed(1)}m`}</span></div>)}{opt.estimated_cost_saved_usd && (<div className="flex items-center gap-2 px-3 py-1.5 bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800 rounded-lg"><span className="text-xs text-emerald-600 dark:text-emerald-400 font-bold">💰 Cost Saved:</span><span className="text-sm font-bold text-emerald-800 dark:text-emerald-300">${opt.estimated_cost_saved_usd.toFixed(2)}/run</span></div>)}{opt.implementation_complexity && (<div className="flex items-center gap-2 px-3 py-1.5 bg-purple-50 dark:bg-purple-900/20 border border-purple-200 dark:border-purple-800 rounded-lg"><span className="text-xs text-purple-600 dark:text-purple-400 font-bold">🔧 Complexity:</span><span className={`text-sm font-bold ${opt.implementation_complexity === 'Low' ? 'text-emerald-700 dark:text-emerald-400' : opt.implementation_complexity === 'Medium' ? 'text-amber-700 dark:text-amber-400' : 'text-red-700 dark:text-red-400'}`}>{opt.implementation_complexity}</span></div>)}</div>)}
                {opt.affected_stages && opt.affected_stages.length > 0 && (<div className="mt-3 flex items-center gap-2 text-xs text-slate-600 dark:text-slate-400"><span className="font-semibold">Affects Stages:</span><div className="flex gap-1 flex-wrap">{opt.affected_stages.map((stage, i) => (<span key={i} className="px-2 py-0.5 bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded font-mono font-bold text-slate-700 dark:text-slate-300">{stage}</span>))}</div></div>)}
              </div>
            </div>
            <span className={`text-xs font-bold px-4 py-2 rounded-full uppercase tracking-wider flex-shrink-0 border shadow-sm ${opt.severity === Severity.HIGH ? 'bg-white dark:bg-slate-800 border-red-200 dark:border-red-900 text-red-700 dark:text-red-400' : opt.severity === Severity.MEDIUM ? 'bg-white dark:bg-slate-800 border-amber-200 dark:border-amber-900 text-amber-700 dark:text-amber-400' : 'bg-white dark:bg-slate-800 border-emerald-200 dark:border-emerald-900 text-emerald-700 dark:text-emerald-400'}`}>{opt.severity} Priority</span>
          </div>
          {opt.codeSuggestion && (<div className="border-t border-slate-200 dark:border-slate-800 grid grid-cols-1 lg:grid-cols-2 divide-y lg:divide-y-0 lg:divide-x divide-slate-200 dark:divide-slate-800">{opt.originalPattern && (<div className="p-6 bg-slate-50 dark:bg-slate-900/50"><div className="flex items-center gap-2 text-xs font-bold text-red-700 dark:text-red-400 uppercase mb-4 tracking-wider"><AlertTriangle className="w-3 h-3" /> Current Pattern</div><div className="font-mono text-sm text-slate-800 dark:text-slate-200 bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-200 dark:border-slate-700 shadow-inner font-medium"><pre className="whitespace-pre-wrap break-words">{opt.originalPattern}</pre></div></div>)}<div className={`p-6 bg-white dark:bg-slate-900 relative ${!opt.originalPattern ? 'col-span-2' : ''}`}><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2 text-xs font-bold text-emerald-700 dark:text-emerald-400 uppercase tracking-wider"><Code className="w-3 h-3" /> Optimized Code</div><button onClick={() => copyToClipboard(opt.codeSuggestion!, idx)} className="flex items-center gap-2 text-xs px-3 py-1.5 rounded-lg bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-700 transition-all font-bold shadow-sm">{copiedIdx === idx ? <CheckCircle className="w-3 h-3 text-emerald-600" /> : <Copy className="w-3 h-3" />}{copiedIdx === idx ? "Copied" : "Copy"}</button></div><div className="relative"><pre className="relative text-sm font-mono text-emerald-800 dark:text-emerald-200 overflow-x-auto p-4 bg-emerald-50 dark:bg-emerald-950/20 rounded-xl border border-emerald-100 dark:border-emerald-900 shadow-inner font-medium"><code>{opt.codeSuggestion}</code></pre></div></div></div>)}
        </div>
      ))}
    </div>
  );
};